### ISSUE TITLE
Moving application disables or cripples it

### ISSUE THREAD

**Issue by a-einstein** [pylerSM/YouTubeBackgroundPlayback#130]
After initial installation it seemed to work all right.

But after I routinely moved the application to the external SD card it failed, of at least became crippled. I found 'File not founds' about it in the log file of Xposed Installer. After moving it back it seems to work again.

Apparently the moving was not supported. I do not know if it would be possible at all, but if not then it should be avoided or be warned for.

**Comment by iHelp101** [comment]
This is because of Xposed. Xposed starts during your devices booting sequence. Your SD Card however is not mounted until the device fully boots. This prevents Xposed from loading the SD Card, which contains the module. @esgie add the code below to the AndroidManifest.xml file (Within application) to prevent the option to move to SD Cards.

android:installLocation="internalOnly"

**Comment by esgie** [comment]
Will be added in the next release. Thanks.
