### ISSUE TITLE
Why a always update?

### ISSUE THREAD

**Issue by benrap** [pylerSM/YouTubeBackgroundPlayback#153]
I may hace not searched the threads here well enough, but why the heck does this module need an update EVERY SINGLE F***ING TIME YouTube gets updated? I am no coder so I couldn't understand your code too much, but from what I saw all you do is set a boolean to true, and then youtube simply takes that as a positive to bg playback. So what do you change every time, and is there a possible way to make a module compatible for all yt versions with no significant changes?

**Comment by iHelp101** [comment]
You are correct about changing the boolean to true. However you have to understand the boolean's location changes in almost every update. The location is the java class the boolean is in. Google/YouTube does this because the module makes a paid feature free. 

They of course want to disrupt the module since in theory it hurts Google/YouTube. In terms of a method that works for every version this is not possible to my knowledge. Certain things can be done to make updating hooks easier.

For example, hooks can be hosted in a text file on GitHub. This allows the maintainer to update the hooks without having to release a new APK.

**Comment by benrap** [comment]
Thanks for the reply!!!
You did answer my questions, and now I have one more (kind of repeated one): could it be somehow possible, to simply find the line of code faster, in some kind of other way. Or maybe mimic the info sent from some Google server to the YouTube app - so that you don't even need to chamge the code of "does he have yt red?", and all you need to change is "this is Google server number 1234 reporting and saying account number 666420 has yt red".
Could this be a thing? Or do i have to cope with slow updates for now? It's just that i live where we don't have yt red and really like bg playback.

**Comment by iHelp101** [comment]
It is possible to find the line of code faster. You can make a python program to decompile the latest APK and find the hooks. The issues is at the moment the module still requires a manual APK update. This is why I suggested the option to host the hooks file on GitHub instead of hard coding them in. This makes updates have less of an effect on the module.

In terms of spoofing or manipulating an API request I don't believe this would be an easy thing to do. It is a user privacy issue when you have the ability to intercept traffic. At the moment you are stuck with the slow updates. The module maintained by @esgie and @pylerSM. It is their decision how they would like to resolve Google/Youtube countering the module.

**Comment by benrap** [comment]
Thanks @iHelp101 !! This is good info. If pyler and esgie don't know of this yet (I highly doubt that), let's hope they'll chime in and make this module even better!!!

**Comment by rainbowdashie1** [comment]
@iHelp101, would you be interested in merging XInsta's hooks updating into this sometime?

**Comment by pylerSM** [comment]
I can imagine: Module could check if YT app was updated, if so, we could download hooks data from github json file, for example.

I believe I will have some free time (university summer terms finished! yes!) so I could look on it in a next few days...

**Comment by benrap** [comment]
Thanks so much pyler!!!

**Comment by pylerSM** [comment]
`{
  "111852": {
    "CLASS_1": "qit",
    "METHOD_1": "d",
    "FIELD_1": "e",
    "SUBFIELD_1": "f",
    "CLASS_2": "ndv",
    "METHOD_2": "a",
    "FIELD_2": "a",
    "CLASS_3": "cba",
    "METHOD_3": "d"
  }
}`

**Comment by Phoenix09** [comment]
I would love to help but unfortunately I don't know Java
I have added support for YouTube v11.19.56 though

**Comment by Phoenix09** [comment]
I converted the Java arrays to PHP and made a script to generate the JSON (#165)
I also made a script to update the JSON to reduce the chance of breaking it, it would be useful if someone made a python version, @NHellFire?

@NHellFire has a WIP that downloads the hooks, it currently doesn't use them and needs some clean up
it will silently attempt to update the hooks when the module or YouTube is updated and notify if they were updated

**Comment by iHelp101** [comment]
@Phoenix09 Thank you for helping the push towards remote hooks. 

All we need now is to add an HTTP request to get the JSON file, a method to parse the file and get the correct hooks (Compare version code to version code installed on device), and a method to save the hooks (XSharedPreferences is likely going to be the best option).

The hooks file should be hosted on another source as well. GitHub is blocked by some governments, ISPs, etc.

**Comment by pylerSM** [comment]
My idea: Try to update hooks when:
- Youtube app is launched (for sure)
- Youtube app has been upgraded. (for sure)
- Device is booted (not sure if really needed imho, yes/no?)

So I would start here during this week...

Things like where to host hooks file could be solved then, thought. But you can share ideas for it even now...


Any scripts (to generate/append json file or analyze apk for new hook values) are welcomed too.. :)

**Comment by pylerSM** [comment]
oh and...

@Phoenix09 thank you for your help, good job!

**Comment by iHelp101** [comment]
@pylerSM Don't do the check on boot because it can take a few seconds for Wi-Fi to connect completely. Do it every time the module starts (When Youtube is loaded). I tried parsing the JSON Array, but I am not sure about the format. 

You can first try the obfuscated check (Maybe just hard code these hook in instead of having it in the hook file). You will get the hook file if the check fails, which then gets parsed to get the version. If you matched the versions you have your hooks. If the JSON file is missing the version you can default to the latest hooks if desired. Once the hooks are found save them via XSharedPreferences (Always hooks to not have to fetched every time). 

I have mostly everything working. I just can't figure out how to parse the JSON file.

**Comment by pylerSM** [comment]
So push what you have so I can work on it and not reinvent what you have :) Can u? :)

**Comment by Phoenix09** [comment]
something like this?
```java
try {
	JSONObject reader = new JSONObject(jsonString);
	JSONObject hooks = reader.getJSONObject(versionCode);
	public static final String CLASS_1 = hooks.getString("CLASS_1");
	// etc
} catch (JSONException e) {
	e.printStackTrace();
}
```

**Comment by iHelp101** [comment]
@pylerSM I added a pushed my testing version.

**Comment by iHelp101** [comment]
@pylerSM I found the issue. It is working nicely now (From my small testing). The only thing missing is a method to save the hooks. XSharedPreferences will likely work well. Every time I personally mess with XSharedPrefences I cause a bootloop, so I am avoiding that part.

After you find a saving method all you need to do is add a check in the beginning. You compare the version that is saved (XSharedPreferences) to the version installed. It the version matched you go straight to hookYoutube(). If not you start the hooks check. 

https://github.com/pylerSM/YouTubeBackgroundPlayback/blob/master/YouTubeBackgroundPlayback-Testing.java

**Comment by pylerSM** [comment]
I believe this (downloading hooks) needs to be moved to Broadcast Receiver. So we can save data to SharedPrefs.

**Comment by pylerSM** [comment]
Did you mean VERSION: 1 as a problem?


https://github.com/pylerSM/XposedManager/blob/master/app/src/main/java/com/pyler/xposedmanager/XposedManagerActivity.java#L214

so maybe this will work?
if (jsonObject.has("VERSION")) {
    hookFileVer = jsonObject.getInt("VERSION");
}

**Comment by pylerSM** [comment]
I created branch **remote hooks**

**Comment by iHelp101** [comment]
@pylerSM That works. I will add some code to it to send the broadcast. I will not do the XSharedPreferences part. I always cause bootloops with XSharedPreferences.

**Comment by pylerSM** [comment]
Okey, push (comment) even code which fails, i will check it.

**Comment by iHelp101** [comment]
@pylerSM The broadcast can handle saving the hooks. The module can do the check and then send the hooks to the broadcast receiver to save the hooks. How do you want to have the hooks? Do you just want to parse them and save them one by one? Or maybe save them in one string, but each hook is separated by a comma (Allows you to split the comma's).

**Comment by iHelp101** [comment]
I just remember you can't receive an broadcast receiver if the app is never opened (Security). We can just change it to an IntentService.

**Comment by Phoenix09** [comment]
@iHelp101, maybe just save the relevant hooks and the version code?
then attempt to update the hooks if the saved version doesn't match the youtube version

something like:
```java
JSONObject hooksObject = jsonObject.getJSONObject(versionCode);
CLASS_1 = hooksObject.getString("CLASS_1");
CLASS_2 = hooksObject.getString("CLASS_2");
CLASS_3 = hooksObject.getString("CLASS_3");
METHOD_1 = hooksObject.getString("METHOD_1");
METHOD_2 = hooksObject.getString("METHOD_2");
METHOD_3 = hooksObject.getString("METHOD_3");
FIELD_1 = hooksObject.getString("FIELD_1");
FIELD_2 = hooksObject.getString("FIELD_2");
SUBFIELD_1 = hooksObject.getString("SUBFIELD_1");

SharedPreferences prefs = context.getSharedPreferences("hooks", Context.MODE_PRIVATE);
SharedPreferences.Editor editor = prefs.edit();
editor.putString("VERSION", versionCode);
editor.putString("CLASS_1", CLASS_1);
editor.putString("CLASS_2", CLASS_2);
editor.putString("CLASS_3", CLASS_3);
editor.putString("METHOD_1", METHOD_1);
editor.putString("METHOD_2", METHOD_2);
editor.putString("METHOD_3", METHOD_3);
editor.putString("FIELD_1", FIELD_1);
editor.putString("FIELD_2", FIELD_2);
editor.putString("SUBFIELD_1", SUBFIELD_1);
editor.apply();
```

my Java experience is limited to small modifications in existing apps so I'm not really sure how to implement that in this module.

**Comment by iHelp101** [comment]
I went with just adding commas and putting them in one string. I personally use this method because if that SharedPreference is not saved you only having to deal with one. If you have ten SharedPreferences you have to make sure their strings exist (Ten extra if statements). Feel free to change the code to your liking. I added the XSharedPreferences part, but please double check it and test it.

From my testing everything is playing nicely. Hooks are saving, updating when a new version is installed on the device, and fetching.

**Comment by Phoenix09** [comment]
working fine

these lines need correcting:
`METHOD_2 = hooksObject.getString("METHOD_1");`
`METHOD_3 = hooksObject.getString("METHOD_1");`
`FIELD_2 = hooksObject.getString("FIELD_1");`

hooks URL needs to be changed to master instead of a commit

@iHelp101, just wondering, what's the reason for the while loop instead of doing `JSONObject hooksObject = jsonObject.getJSONObject(version);` and wrapping it in a try block?

**Comment by iHelp101** [comment]
@Phoenix09 That would be better. When I originally saw you mention that I didn't realize the mistake I made. I am going to let Pyler take over. Thanks for the help.

**Comment by jkdf2** [comment]
This has been addressed in the latest experimental build.

**Comment by benrap** [comment]
Cool!!!
