### ISSUE TITLE
when in background OOM conditions Kills Youtube Or Greenify

### ISSUE THREAD

**Issue by shaktishekhar** [pylerSM/YouTubeBackgroundPlayback#189]
Give the you tube PID as Foreground-background process until its playing so that it wont get killed..

**Comment by sigv** [comment]
With all due respect, I must ask how this is an issue with the YouTube application or this Xposed module.

I believe Greenify is doing what it is expected to do in that condition - stepping in to stop YouTube running in the background - in which case I do not believe we (nor Google) should in any way circumvent that using any hacks and workarounds. If Greenify allows whitelisting specific packages/applications, that method should be used to work around this issue. If that is not the case, I believe an issue should be opened with the Greenify maintainers instead of us so that they can allow whitelisting specific packages/applications.
