### ISSUE TITLE
Screen won't turn on during background playback

### ISSUE THREAD

**Issue by MattLyte** [pylerSM/YouTubeBackgroundPlayback#218]
When trying to turn my screen back on during background playback, it lights up black but hangs there, and I have to turn it off and back on multiple times to get it to work.

It seems related to the low-power state my phone (Moto X Play, 2015) has, called Moto Display. It lights up in a low power state when the phone moves while off, displaying the clock and some limited notifications from certain apps (usually just play/skip buttons for music players.) While this issue is happening, moto display does not light up at all. If I block YT's notification from appearing in moto display, both it and screen-on work normally again.

This never used to happen, but when the signature update issues with YTBP began, I was unable to install the new version even after uninstalling the old. After trying everything else, I reflashed a NAND backup taken just after unlocking my device, which had never had xposed or anything else installed, and installed the latest version of YTBP fine. However, it was after this that I noticed this screen-on issue.

It is strange because it is definitely a conflict of some sort, (disabling YT from appearing in moto display stops the issue,) but prior to reflashing because I could not update, it never occurred and I could control the YT notification through moto display just fine. As the update issue began I noticed a beta version with different notification visibility. Perhaps the change in notification code created the conflict?

**Comment by th3an7** [comment]
Have you tried both versions of module (stable and beta)? One has notification always visible, the other has notification only when YT is in background.

What system are you now on? Stock or custom? Can you disable Moto Display completely? (I guess it's something like Ambient Display, right?)

I don't think it's because of the module. Google has changed YT app code. The module only makes notification appear for those without YouTube Red subscription.

On OmniRom 5.1.1 on my Xperia M2, I had Ambient Display. It allowed me to peek notification without turning the screen on (everything was black, only notifications were visible with inverted colours). There was no conflict between YT app, module and that OmniRom feature.

**Comment by MattLyte** [comment]
I tried the beta just after posting this. No difference.

I'm on stock. A NAND taken just after I unlocked the device.

I can disable Moto Display (it is similar to ambient display, although different in exact functionality/implementation.)  As I said, it's a conflict between Moto Display and YT Background Playback, that was not occurring before I reflashed to update the module. Maybe the module, maybe just the feature itself. I can't tell because I don't have youtube red.

I managed to stop it from occurring by blocking the YT notification from appearing in Moto Display. I just wanted to post this in case it helped pyler or anyone else identify an obvious but overlooked bug or incompatibility.

I see nothing in the xposed log about it, and don't know how else to provide detailed info about what's going on, so I don't expect a fix unless they happen to have a recent Moto device, which I wouldn't recommend buying. Great feature ideas, but not responsive or smooth enough to make them useful, plus a bunch of random-ass bugs like this to boot.
