### ISSUE TITLE
No Close Button anymore?

### ISSUE THREAD

**Issue by Brainc0re** [pylerSM/YouTubeBackgroundPlayback#220]
I updated the app to the current Version 1.8.29 and the close button "X" is missing in the notification. I tried to reinstall the app - but still missing.

https://abload.de/img/screenshot_20160813-1imu8r.jpg

**Comment by th3an7** [comment]
That's Google fault. Module does not create it - it only makes it visible.

Also - that's strange because on mine there is completely different notification

![screenshot_2016-08-13-14-23-53](https://cloud.githubusercontent.com/assets/13398380/17643175/f7a293f4-6161-11e6-8f32-0f69fd09521c.png)

**Comment by pylerSM** [comment]
.setPriority(Notification.PRIORITY_MAX)
.setWhen(0)

For notification..

th3an7 maybe you can try this :D

**Comment by th3an7** [comment]
Sure, If you could tell me what exactly I need to do, that would be perfect :P
or
push commit to my forked repo... (if it's possible)

**Comment by iHelp101** [comment]
@th3an7 You would need to hook the notification. That would involve finding where this specific notification is made. You could for example look for "NotificationCompat.Builder" in YouTube's code. Once you have the notification you would add the additional parameters pyler mentioned to the notification.

**Comment by th3an7** [comment]
Oh, ok :)
I will try this

**Comment by th3an7** [comment]
I am sitting now like 2,5h straight looking for this stupid line and I found 2 or 3 of these but they are called "Notification.Builder". There is such in "hmx" and "ii" classes.

But I also found out that there are classes that controlls notification buttons - what is shown and what is not (at least it looks like that for me - for youtube 11.29.54 that's "rye" and "ryf".

Also - can notification design be connected with application DPI? I am using App Settings module to change YT app DPI for 720p video quality option. Maybe that's why I have different notification than OP?

**Comment by iHelp101** [comment]
@th3an7 Notification.Builder may work. Anyway you can get the notification may work. You have to hook into and set an output. You keep trying different classes and methods until you find one that outputs when the notification appears. 

I have not looked into YouTube's code for a while, but from what I remember it is very obfuscated.

**Comment by pylerSM** [comment]
You dont need to mess with obfuscated code. Just hook NotificationManager.notify, take second (?) arg (notification) in before hooked method, apply priority and setWhen and done.
