### ISSUE TITLE
New YT version - backplay not work

### ISSUE THREAD

**Issue by titanus77** [pylerSM/YouTubeBackgroundPlayback#256]
Hi. 

3-4  days ago YT was actualised on my OPT A2003,  and now background play with YT version 11.41.56 and YT background playback in version 1.8.36 not work. 

Peter.

**Comment by th3an7** [comment]
Latest version is 1.8.39... Check repo if it's not visible in Xposed app...

Module supporting latest YT app is always uploaded max 2 days after new YT
app is uploaded to ex. apkmirror.com (very late updates of YT in play store)

On Wed, Nov 2, 2016, 20:47 titanus77 <notifications@github.com> wrote:

Hi.

3-4 days ago YT was actualised on my OPT A2003, and now background play
with YT version 11.41.56 and YT background playback in version 1.8.36 not
work.

Peter.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/256>, or mute
the thread

**Comment by Fohdeesha** [comment]
1.8.39 does not work with the latest YouTube, 11.43.52, and it's been out a lot longer than two days....

**Comment by th3an7** [comment]
Yeah, I know... I couldn't upload already updated apk because repo was offline (we couldn't log in into that...)

Also, we are almost ready for a big update - we are just waiting for owner to respond. That is also why apk is not yet in repo... I can upload apk here (temporarily) so we wouldn't have 2 the same releases on repo :P

Notification visible all the time - https://drive.google.com/file/d/0B8j7vCsf6RXcUUtzMXEyYzcwYW8/view?usp=sharing

Notification visible only in background - https://drive.google.com/file/d/0B8j7vCsf6RXcT0Rxd08tVGd2ZW8/view?usp=sharing
