### ISSUE TITLE
Make APK with patches?

### ISSUE THREAD

**Issue by BeastMode6** [pylerSM/YouTubeBackgroundPlayback#298]
Hello. If the xposed module patches the app, couldn't I just backup the app with titanium and update to nougat, keeping the background playback?

**Comment by esgie** [comment]
No.
Xposed module doesn't patch the app. It hooks at runtime and changes its
behavior on the fly.
You are speaking about the other way to achieve background playback. You
can "patch" the Youtube app using the application named Lucky Patcher using
my custom patch, which is indeed based on the module. You can patch it when
installed if rooted and this is the ONLY recommended way. Also, you can
rebuild a patched apk even if not rooted, but you won't be able to install
it over built-in Youtube app and even if, signing into your account won't
work, all of the above due to signature mismatch.
And yes, Lucky Patcher DOES work on rooted Nougat... for some, but does not
for others ;)
But if you're on rooted 7.x and can't live without background playback, you
may want to try it.
pzdr
es

24 sty 2017 18:37 "BeastMode6" <notifications@github.com> napisał(a):

Hello. If the xposed module patches the app, couldn't I just backup the app
with titanium and update to nougat, keeping the background playback?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/298>, or mute
the thread

**Comment by BeastMode6** [comment]
Well right now I am on Marshmallow, but I really want to upgrade to Nougat. I absolutely cannot live without background playback :P. Couldn't you patch GPlay Services to allow for sign in on mismatched signatures?

**Comment by BeastMode6** [comment]
Well right now I am on Marshmallow, but I really want to upgrade to Nougat. I absolutely cannot live without background playback :P. Couldn't you patch GPlay Services to allow for sign in on mismatched signatures?

**Comment by th3an7** [comment]
As @esgie said - just use Lucky Patcher - I am myself on 7.1.1 and it's working fine - just like the module. It plays videos in background and displays notification. You just need to be rooted :P

**Comment by BeastMode6** [comment]
I got it, using the lucky patcher method. I was even able to stay signed in.

**Comment by aixki** [comment]
Works fine with custom patch and lucky patcher here. Did you guys also found a way to remove these annoying ads ?
