### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by FFlipe** [pylerSM/YouTubeBackgroundPlayback#299]
Hello , 

I was looking for an APP to YT then I got you project , actually I am having cyanogen with  YT version 12.01.55 
I have done a download but it is not working as well .
Could someone else help me to use this nice app ?

Cheers

**Comment by th3an7** [comment]
Which CM are you running? Is Xposed active as well as the module? Which
version of module are you running?

**Comment by FFlipe** [comment]
I am using cm 13 with galaxy s3 from wind sgh t999v canadian 
Version 13.0-20161211nigthly-d2tmo

Thank you so much for your attention

**Comment by FFlipe** [comment]
Kernel version  3.4.112 
Build 6.0.1MOB31k

**Comment by FFlipe** [comment]
Package: 
com.pyler.youtubebackgroundplayback
Version name: 
2.0.1
Release type: 
Stable (low risk of bugs)
Download: 
com.pyler.youtubebackgroundplayback_v20010_42a0c8.apk (31.24 KB)
Number of downloads

**Comment by esgie** [comment]
You did install xposed framework to the system before and you did enable
the module in xposed installer, didn't you?
If so, then please post Youtube app version and xposed log.
Otherwise, if you have no xposed but you're rooted, you may want to try the
other solution, the Lucky Patcher patch.

pzdr
es


26 sty 2017 19:48 "FFlipe" <notifications@github.com> napisał(a):

Package:
com.pyler.youtubebackgroundplayback
Version name:
2.0.1
Release type:
Stable (low risk of bugs)
Download:
com.pyler.youtubebackgroundplayback_v20010_42a0c8.apk (31.24 KB)
Number of downloads

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/299#issuecomment-275475385>,
or mute the thread

**Comment by FFlipe** [comment]
I did it but the xposed framework says is not installed but I did it before .

Where can I have the correct ones to do it (sorry to the basic question because I am new one on it )

Thank you so much

**Comment by esgie** [comment]
You have to flash xposed framework via recovery.
Please refer here: https://forum.xda-developers.com/showthread.php?t=3034811

pzdr
es


26 sty 2017 21:59 "FFlipe" <notifications@github.com> napisał(a):

I did it but the xposed framework says is not installed but I did it before
.

Where can I have the correct ones to do it (sorry to the basic question
because I am new one on it )

Thank you so much

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/299#issuecomment-275511743>,
or mute the thread

**Comment by FFlipe** [comment]
You guys Helped me alot !!!
Thank you so much .

So does the project have an biticon address  to make a donte for ?
It'd be nice to help you guys , this an app is very USEFUL

Cheers
