### ISSUE TITLE
12.23.60 doesnt work

### ISSUE THREAD

**Issue by SirPirate** [pylerSM/YouTubeBackgroundPlayback#332]
Hello,
today I install YouTubeBackgroundPlayback and doesnt work in youtube 12.23.60

**Comment by th3an7** [comment]
Which module version are you using?

**Comment by firozpatel123** [comment]
Module version 2.0.2 works with latest youtube update, where as module version 2.0.4 does not work, just a heads up for those who is trying to make it work with 2.0.4

**Comment by th3an7** [comment]
It should work for both 2.0.2 and latest 2.0.4 as hooks for YT 12.23.60 are the same.
Post a logcat if it does not work...

**Comment by firozpatel123** [comment]
I tried 2.0.4 again, forced closed youtube, reboot and its working like a charm, thanks for the good work

**Comment by djstrattos** [comment]
Good day mate,
Below my specs.
Doesn't seem to be working with 2.0.2 or 2.0.4 with the latest YT version.
As I don't know what to expect with a working version since I don't see anything changed in YT I suppose I have issues. Could you please have a look and propose something?
Seems really promising and I eager to get it work😀
![screenshot_2017-07-09-14-53-49-465_com android settings](https://user-images.githubusercontent.com/6215372/27993724-d5e0dba4-64b7-11e7-8714-7fded26775d9.png)
![screenshot_2017-07-09-14-52-51-077_com android settings](https://user-images.githubusercontent.com/6215372/27993725-d5e41ec2-64b7-11e7-8125-0724952f6b2b.png)
![screenshot_2017-07-09-14-52-24-033_com android settings](https://user-images.githubusercontent.com/6215372/27993726-d5e99db6-64b7-11e7-88a8-b7284b07b0fb.png)
![screenshot_2017-07-09-14-52-44-950_com android settings](https://user-images.githubusercontent.com/6215372/27993727-d5ec97e6-64b7-11e7-97ff-b5ac1d315060.png)

**Comment by djstrattos** [comment]
@th3an7 hahahaah OK m8 now you are talking! :D
