### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by ryan96521** [pylerSM/YouTubeBackgroundPlayback#36]
Downgrade youtube to this version for now until dev fixes the newer versions. 
Uninstall youtube then install this and reboot!

http://www.apkmirror.com/apk/google-inc/youtube/youtube-10-08-52-android-apk-download/

**Comment by esgie** [comment]
In the other thread I have uploaded a build with improved YouTube version detection.
It should support ALL YouTube versions and sub-versions (!) from 10.02.xx to 10.13.xx
http://www66.zippyshare.com/v/K6nqaBHP/file.html
(may require uninstalling previous version due to signature mismatch)
Also sent a commit to a dev so he may include this in an official release :)

**Comment by ryan96521** [comment]
Some people like me cant use Zippyshare due to many ads that redirect and dont give you the folder. Upload that to MegaFile or dropbox that would be easyier

**Comment by esgie** [comment]
http://www.megafileupload.com/30PT/ytbgp_141test1.apk
