### ISSUE TITLE
Support for YT 10.42.xx

### ISSUE THREAD

**Issue by miladmaz12** [pylerSM/YouTubeBackgroundPlayback#79]
http://www.apkmirror.com/apk/google-inc/youtube/youtube-10-42-52-nodpi-android-6-0-android-apk-download/

**Comment by esgie** [comment]
Don't have any testing device capable of running this.
We'll have to wait for lollipop release. Hope it will be available today.

**Comment by miladmaz12** [comment]
@esgie 

https://www.apkmirror.com/apk/google-inc/youtube/youtube-10-43-58-android-4-0-3-5-1-android-apk-download/

**Comment by esgie** [comment]
Some code has changed (in the first class, especially - but it still has the triggering code!), although hacks are still working :)
New version with support for 10.43 is up.
Added also theoretical support for yt 10.42 which has been released for marshmallow only. It won't be much use because no xposed for marshmallow atm, but it's there...

**Comment by miladmaz12** [comment]
@esgie Ok, thanks! I'll close this now
